version: '3'
services:
  nginx:
    build:
      context: docker/nginx
      args:
        PHP_UPSTREAM: php
        UID: 501
        GID: 20
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - .:/var/www/application
  php:
    build:
      context: docker/php-fpm
      args:
        UID: 501
        GID: 20
    volumes:
      - .:/var/www/application
  cli:
    build:
      context: docker/php-cli
      args:
        UID: 501
        GID: 20
    volumes:
      - .:/var/www/application
  worker:
    build:
      context: docker/worker
      args:
        UID: 501
        GID: 20
    volumes:
      - .:/var/www/application
  workspace:
    build:
      context: docker/workspace
      args:
        UID: 501
        GID: 20
    volumes:
      - .:/var/www/application
  db:
    image: "mariadb"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: atom-feed
      MYSQL_DATABASE: atom-feed
      MYSQL_USER: atom-feed
      MYSQL_PASSWORD: atom-feed
    volumes:
      - dbdata:/var/lib/mysql
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  dbdata:
  redisdata: